#! /bin/bash -e

REPOSITORY="mylib/hello-spring"


cd $(dirname ${BASH_SOURCE[0]})/..

./auto/dev gradle clean build

docker build --build-arg JAR_FILE=./build/libs/hello-spring-latest.jar \
 -t ${REPOSITORY}:${BUILD_NUMBER-DEV} .

# docker push ${REPOSITORY}:${FULL_VERSION}
# docker tag ${REPOSITORY}:${FULL_VERSION} ${REPOSITORY}:latest
# docker push ${REPOSITORY}:latest
